# -*- coding: utf-8 -*-
"""mod1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Igqprz_llP8KzsJaLCanD-WRtN4fT3B
"""

def add(a,b):
    return a+b

def sub(a,b):
    return a-b

print('mod1이 실행되었습니다.')