# -*- coding: utf-8 -*-
"""mod2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc751EmZKj6wXhLtIL9RVOQDVMXPITzi
"""

import math

class Circle():
    def calculate_circle_area(self,radius):
        if radius < 0:
            return "반지름은 음수가 될 수 없습니다."
        else:
            area = math.pi * radius ** 2
            return area