# -*- coding: utf-8 -*-
"""mod3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xY3U2wZMorwfQgHHvd3zFPjhf4PhS0Yw
"""

def mul(a,b):
    return a*b